import test from 'node:test';
import assert from 'node:assert/strict';
import {quote} from '../src/core/quote.mjs';
import {selfcheck} from '../src/core/selfcheck.mjs';
import {gauntlet} from '../src/core/gauntlet.mjs';
import {startFixture} from '../fixtures/server.mjs';
import {arenaCard,arenaMarkdown} from '../src/server/arena-card.mjs';

test('quote maps every intent to a priced service',()=>{const expected={preflight:['sledgewire.smoke',3],adversarial:['sledgewire.assay',8],repair_execute:['sledgewire.invoke',12],compare:['sledgewire.fleet',20],certify:['sledgewire.seal',25],full_dossier:['sledgewire.gauntlet',35]};for(const [intent,[service,price]] of Object.entries(expected)){const q=quote({intent,endpoint:'https://example.com/mcp'});assert.equal(q.recommended_service,service);assert.equal(q.price_credits,price);assert.equal(q.request_template.service,service);}});
test('quote accepts deterministic buyer-language aliases and rejects unknown intent',()=>{const cases={check:'sledgewire.smoke',security:'sledgewire.assay',repair:'sledgewire.invoke',choose:'sledgewire.fleet',conformance:'sledgewire.seal',dossier:'sledgewire.gauntlet'};for(const [intent,service] of Object.entries(cases)){const args=service==='sledgewire.fleet'?{intent,targets:[{endpoint:'https://example.com/mcp'}]}:{intent,endpoint:'https://example.com/mcp',...(service==='sledgewire.invoke'?{tool:'safe_echo'}:{})};const q=quote(args);assert.equal(q.recommended_service,service);assert.equal(q.matched_rule,'intent_alias');assert.equal(q.value_proof.exact_retry_no_reexecution,true);}assert.throws(()=>quote({intent:'magic'}),/unsupported_quote_intent/);});
test('quote marks incomplete templates instead of presenting them as send-ready',()=>{
  const q=quote({intent:'preflight'});assert.equal(q.request_ready,false);assert.deepEqual(q.missing_fields,['endpoint']);assert.equal(q.input_validation.reason,'missing_required_quote_context');
  const invoke=quote({intent:'repair_execute',endpoint:'https://example.com/mcp'});assert.equal(invoke.request_ready,false);assert.ok(invoke.missing_fields.includes('tool'));
});
test('quote marks structurally valid paid templates send-ready',()=>{
  const smoke=quote({intent:'preflight',endpoint:'https://example.com/mcp'});assert.equal(smoke.request_ready,true);assert.deepEqual(smoke.missing_fields,[]);
  const fleet=quote({intent:'compare',targets:[{endpoint:'https://example.com/mcp'}]});assert.equal(fleet.request_ready,true);
});
test('selfcheck covers modern and hostile fixture expectations',async()=>{const r=await selfcheck();assert.equal(r.verified,true);assert.equal(r.state,'READY');assert.equal(r.profile,'sledgewire.selfcheck.v4');assert.equal(r.cases.length,10);assert.ok(r.cases.some(x=>x.mode==='modern'&&x.ok));assert.ok(r.cases.every(x=>x.ok));});
test('gauntlet produces seller dossier on clean service',async()=>{const f=await startFixture();try{const r=await gauntlet(f.url,{targetPolicy:{allowHttp:true,allowPrivate:true},probe:{name:'safe_echo',arguments:{text:'hello'},safe:true,authorizeUnknownToolProbe:true}});assert.equal(r.state,'READY');assert.equal(r.profile,'sledgewire.gauntlet.v1');assert.ok(r.dossier_sha256);assert.equal(r.conformance.profile,'sledgewire.mcp-conformance.v3');}finally{await f.close();}});
test('arena card exposes judge path, low-friction buyer path and verifiable authority proof',()=>{const c=arenaCard('https://sledgewire.example');assert.equal(c.fastest_demo.tool,'sledgewire.selfcheck');assert.equal(c.free_selector.tool,'sledgewire.quote');assert.equal(c.readiness_url,'https://sledgewire.example/ready');assert.equal(c.arena1_judge_path[1].tool,'sledgewire.selfcheck');assert.equal(c.arena2_buyer_path.best_first_paid.price_credits,3);assert.equal(c.proofs.replay.includes('without second execution'),true);assert.equal(c.sharedos_authority.purpose,'sledgewire.test-repair-and-invoke-agent-services');assert.match(c.sharedos_authority.roles.dispatcher,/no target execution grant/);assert.equal(c.sharedos_authority.proof.tool,'sledgewire.trace');assert.equal(c.paid_request_example.type,'sledgewire.service.request.v1');assert.equal(c.paid_request_example.service,'sledgewire.smoke');assert.equal(c.services['sledgewire.gauntlet'].price,35);});
test('arena markdown is a judge-first and buyer-first single-link surface',()=>{const m=arenaMarkdown('https://sledgewire.example');assert.match(m,/30-second judge path/);assert.match(m,/Fast buyer path/);assert.match(m,/Smoke, 3 credits/);assert.match(m,/sledgewire\.selfcheck/);assert.match(m,/https:\/\/sledgewire\.example\/mcp/);assert.match(m,/https:\/\/sledgewire\.example\/ready/);assert.match(m,/buyer-bound signed quote/);assert.match(m,/purpose-bound SharedOS grant/);assert.match(m,/Room text never creates/);});
