import test from 'node:test';import assert from 'node:assert/strict';import {startFixture} from '../fixtures/server.mjs';import {smoke} from '../src/core/smoke.mjs';import {assay} from '../src/core/assay.mjs';import {invoke} from '../src/core/invoke.mjs';import {seal} from '../src/core/seal.mjs';import {fleet} from '../src/core/fleet.mjs';import {boundedRepair,inspectRepair} from '../src/core/repair.mjs';import {validateSchemaValue} from '../src/core/schema.mjs';
const tp={allowHttp:true,allowPrivate:true};const probe={name:'safe_echo',arguments:{text:'ok'},safe:true};
for(const mode of ['clean','injection','description_injection','fake_success','malformed','oversized'])test(`smoke fixture ${mode}`,async()=>{const f=await startFixture({mode});try{const r=await smoke(f.url,{targetPolicy:tp,probe,maxBytes:100_000});const expected={clean:'READY',injection:'DEGRADED',description_injection:'DEGRADED',fake_success:'INCOMPATIBLE',malformed:'INCOMPATIBLE',oversized:'INCOMPATIBLE'}[mode];assert.equal(r.state,expected);}finally{await f.close();}});
test('assay refuses unknown tool',async()=>{const f=await startFixture();try{const r=await assay(f.url,{targetPolicy:tp,probe});assert.equal(r.checks.unknown_tool.status,'pass');}finally{await f.close();}});
test('assay checks forbidden extra arg',async()=>{const f=await startFixture();try{const r=await assay(f.url,{targetPolicy:tp,probe});assert.equal(r.checks.invalid_arguments.status,'pass');}finally{await f.close();}});
test('assay replay on safe idempotent tool is bounded',async()=>{const f=await startFixture({mode:'replay_sensitive'});try{const r=await assay(f.url,{targetPolicy:tp,probe});assert.equal(r.checks.replay.status,'pass');}finally{await f.close();}});
test('invoke repairs integer string and executes',async()=>{const f=await startFixture();try{const r=await invoke(f.url,{name:'safe_echo',arguments:{text:'hello'}},{targetPolicy:tp});assert.equal(r.state,'READY');assert.ok(r.result_sha256);}finally{await f.close();}});
test('invoke refuses missing semantic input',async()=>{const f=await startFixture();try{const r=await invoke(f.url,{name:'safe_echo',arguments:{}},{targetPolicy:tp});assert.equal(r.state,'INCOMPATIBLE');assert.equal(r.repair.status,'needs_information');}finally{await f.close();}});
test('invoke fills missing value only from evidence',async()=>{const f=await startFixture();try{const r=await invoke(f.url,{name:'safe_echo',arguments:{},evidence:{text:'from evidence'}},{targetPolicy:tp});assert.equal(r.state,'READY');assert.equal(r.repair.actions[0].source,'evidence');}finally{await f.close();}});
test('seal has profile version and check ids',async()=>{const f=await startFixture();try{const r=await seal(f.url,{targetPolicy:tp,probe});assert.equal(r.profile,'sledgewire.mcp-conformance.v3');assert.ok(r.checks.every(x=>/^MCP-/.test(x.id)));}finally{await f.close();}});
test('fleet accepts six targets max',async()=>{const f=await startFixture();try{const targets=Array.from({length:6},()=>({endpoint:f.url,probe}));const r=await fleet(targets,{targetPolicy:tp});assert.equal(r.reports.length,6);}finally{await f.close();}});
test('fleet rejects seven targets',async()=>{await assert.rejects(()=>fleet(Array.from({length:7},()=>({endpoint:'x'}))),/1_to_6/);});

const schema={type:'object',required:['n','flag'],additionalProperties:false,properties:{n:{type:'integer',minimum:1,maximum:10},flag:{type:'boolean'},mode:{type:'string',enum:['a','b']}}};
test('repair coerces bounded integer and boolean',()=>{const r=boundedRepair({n:'7',flag:'true'},schema,{});assert.equal(r.status,'repaired');assert.deepEqual(r.args,{n:7,flag:true});});
test('repair rejects unknown field under closed schema',()=>{assert.equal(boundedRepair({n:2,flag:true,x:1},schema,{}).status,'cannot_repair');});
test('repair rejects enum mismatch',()=>{assert.equal(boundedRepair({n:2,flag:true,mode:'z'},schema,{}).status,'cannot_repair');});
test('repair rejects out of range',()=>{assert.equal(boundedRepair({n:20,flag:true},schema,{}).status,'cannot_repair');});
test('repair needs missing info',()=>{assert.equal(boundedRepair({n:2},schema,{}).status,'needs_information');});
test('independent inspector reproduces repair',()=>{const r=boundedRepair({n:'2',flag:'false'},schema,{});assert.equal(inspectRepair({n:'2',flag:'false'},r,schema,{}).status,'pass');});
test('inspector rejects modified candidate',()=>{const r=boundedRepair({n:'2',flag:'false'},schema,{});r.args.n=3;assert.equal(inspectRepair({n:'2',flag:'false'},r,schema,{}).status,'fail');});
for(const [name,value,s,ok] of [
 ['string ok','x',{type:'string',minLength:1},true],['string too short','',{type:'string',minLength:1},false],['integer ok',2,{type:'integer'},true],['integer fail',2.2,{type:'integer'},false],['number fail','2',{type:'number'},false],['boolean fail','true',{type:'boolean'},false],['array ok',[1],{type:'array',items:{type:'integer'},minItems:1},true],['array max',[1,2],{type:'array',maxItems:1},false]
])test(`schema ${name}`,()=>assert.equal(validateSchemaValue(value,s).ok,ok));
test('assay detects server accepting unknown tool',async()=>{const f=await startFixture({mode:'accepts_unknown'});try{const r=await assay(f.url,{targetPolicy:tp,probe});assert.equal(r.checks.unknown_tool.status,'fail');}finally{await f.close();}});
test('assay detects server accepting schema-forbidden field',async()=>{const f=await startFixture({mode:'accepts_extra'});try{const r=await assay(f.url,{targetPolicy:tp,probe});assert.equal(r.checks.invalid_arguments.status,'warn');}finally{await f.close();}});
test('assay warns on divergent replay for declared idempotent tool',async()=>{const f=await startFixture({mode:'divergent_replay'});try{const r=await assay(f.url,{targetPolicy:tp,probe});assert.equal(r.checks.replay.status,'warn');}finally{await f.close();}});
test('smoke blocks destructive target probe without explicit destructive authority',async()=>{const f=await startFixture({mode:'destructive'});try{const r=await smoke(f.url,{targetPolicy:tp,probe});assert.equal(r.state,'BLOCKED');}finally{await f.close();}});
test('streamable SSE fixture works',async()=>{const f=await startFixture({mode:'sse'});try{const r=await smoke(f.url,{targetPolicy:tp,probe});assert.equal(r.state,'READY');}finally{await f.close();}});
test('redirect is refused',async()=>{const f=await startFixture({mode:'redirect'});try{const r=await smoke(f.url,{targetPolicy:tp,probe});assert.equal(r.state,'INCOMPATIBLE');assert.match(r.checks.initialize.reason,/redirect_refused/);}finally{await f.close();}});
test('deadline fails closed',async()=>{const f=await startFixture({mode:'slow'});try{const r=await smoke(f.url,{targetPolicy:tp,probe,timeoutMs:100});assert.equal(r.state,'INCOMPATIBLE');assert.match(r.checks.initialize.reason,/deadline_exceeded/);}finally{await f.close();}});
