import test from 'node:test';import assert from 'node:assert/strict';import {ArenaStore} from '../src/store/arena-store.mjs';import {PaymentGate,paymentMemo,requestFingerprint} from '../src/core/payment-gate.mjs';
const base={roomId:'rom_ABCDEF12',buyerSeat:'i_ABCDEFGHIJ',requestId:'req-1',service:'sledgewire.smoke',input:{endpoint:'https://example.com/mcp'},txnId:'txn_ABCDEFGHIJ'};const payee='p_ABCDEFGHIJ';const prices={'sledgewire.smoke':3};
function ledger(overrides={}){return {async get(){return {id:base.txnId,by_instance_id:base.buyerSeat,addressed_to:payee,amount:3,room_id:base.roomId,memo:paymentMemo(base.requestId,base.service),...overrides};}};}
test('payment required returns exact memo',async()=>{const g=new PaymentGate({ledger:ledger(),store:new ArenaStore(),prices,payee});const r=await g.authorize({...base,txnId:null});assert.equal(r.reason,'payment_required');assert.equal(r.memo,paymentMemo(base.requestId,base.service));});
test('valid payment claims once',async()=>{const s=new ArenaStore(),g=new PaymentGate({ledger:ledger(),store:s,prices,payee});const r=await g.authorize(base);assert.equal(r.ok,true);assert.equal(r.replay,false);});
for(const [name,over,reason] of [['buyer',{by_instance_id:'i_ZYXWVUTSRQ'},'wrong_buyer'],['payee',{addressed_to:'p_ZYXWVUTSRQ'},'wrong_payee'],['amount',{amount:4},'wrong_amount'],['room',{room_id:'rom_OTHER123'},'wrong_room'],['memo',{memo:'bad'},'wrong_memo']])test(`payment rejects wrong ${name}`,async()=>{const g=new PaymentGate({ledger:ledger(over),store:new ArenaStore(),prices,payee});assert.equal((await g.authorize(base)).reason,reason);});
test('completed exact retry returns cached response',async()=>{const s=new ArenaStore(),g=new PaymentGate({ledger:ledger(),store:s,prices,payee});const a=await g.authorize(base);s.complete(base.requestId,a.fingerprint,{delivered:true});const b=await g.authorize(base);assert.equal(b.replay,true);assert.deepEqual(b.cached,{delivered:true});});
test('inflight exact retry does not reexecute',async()=>{const s=new ArenaStore(),g=new PaymentGate({ledger:ledger(),store:s,prices,payee});await g.authorize(base);const b=await g.authorize(base);assert.equal(b.reason,'request_already_inflight');});
test('same txn cannot buy different request',async()=>{const s=new ArenaStore(),g=new PaymentGate({ledger:ledger(),store:s,prices,payee});await g.authorize(base);const other={...base,requestId:'req-2'};const r=await g.authorize(other);assert.equal(r.reason,'wrong_memo');});
test('fingerprint deterministic',()=>assert.equal(requestFingerprint(base),requestFingerprint(base)));
test('failed request never silently reexecutes',async()=>{const s=new ArenaStore(),g=new PaymentGate({ledger:ledger(),store:s,prices,payee});const a=await g.authorize(base);s.fail(base.requestId,a.fingerprint,{message:'boom'});const b=await g.authorize(base);assert.equal(b.reason,'previous_attempt_failed');});
test('bounded grant usage is atomically consumed once',async()=>{const s=new ArenaStore();const results=await Promise.all(Array.from({length:8},()=>s.tryConsume('n','g',1)));assert.equal(results.filter(Boolean).length,1);});
