import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import path from 'node:path';
export class ReplayStore{
  constructor(dbPath=':memory:'){if(dbPath!==':memory:')fs.mkdirSync(path.dirname(path.resolve(dbPath)),{recursive:true});this.db=new DatabaseSync(dbPath);this.db.exec('PRAGMA journal_mode=WAL');this.db.exec('PRAGMA busy_timeout=5000');this.db.exec(`CREATE TABLE IF NOT EXISTS bindings (fingerprint TEXT PRIMARY KEY,txn TEXT UNIQUE NOT NULL,state TEXT NOT NULL CHECK(state IN ('in_flight','complete','failed')),response TEXT,error TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);`);}
  claim(fingerprint,txn){this.db.exec('BEGIN IMMEDIATE');try{const byFp=this.db.prepare('SELECT * FROM bindings WHERE fingerprint=?').get(fingerprint);if(byFp){this.db.exec('COMMIT');return {status:byFp.state==='complete'?'replay':byFp.state==='in_flight'?'in_flight':'failed',response:byFp.response?JSON.parse(byFp.response):null,error:byFp.error??null};}const byTxn=this.db.prepare('SELECT fingerprint FROM bindings WHERE txn=?').get(txn);if(byTxn){this.db.exec('COMMIT');return {status:'txn_reused'};}const now=Date.now();this.db.prepare("INSERT INTO bindings(fingerprint,txn,state,response,error,created_at,updated_at) VALUES(?,?,'in_flight',NULL,NULL,?,?)").run(fingerprint,txn,now,now);this.db.exec('COMMIT');return {status:'claimed'};}catch(e){this.db.exec('ROLLBACK');throw e;}}
  complete(fingerprint,response){const r=this.db.prepare("UPDATE bindings SET state='complete',response=?,error=NULL,updated_at=? WHERE fingerprint=? AND state='in_flight'").run(JSON.stringify(response),Date.now(),fingerprint);if(r.changes!==1)throw new Error('replay_complete_invalid_state');}
  fail(fingerprint,error,response=null){const r=this.db.prepare("UPDATE bindings SET state='failed',response=?,error=?,updated_at=? WHERE fingerprint=? AND state='in_flight'").run(response===null?null:JSON.stringify(response),String(error),Date.now(),fingerprint);if(r.changes!==1)throw new Error('replay_fail_invalid_state');}
  get(fingerprint){const row=this.db.prepare('SELECT * FROM bindings WHERE fingerprint=?').get(fingerprint);return row?{...row,response:row.response?JSON.parse(row.response):null}:null;}
  close(){this.db.close();}
}
